require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  Exclude:
    - 'qmk/zsa_qmk_firmware/**/*'
    - 'vim/.vim/pack/**/*'
    - 'vendor/bundle/**/*'
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false
Style/AsciiComments:
  Enabled: false
