tap "goles/battery"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

brew "bat"
brew "black"
brew "colordiff"
brew "diff-so-fancy"
brew "fortune"
brew "git"
brew "goles/battery/battery"
brew "less"
brew "python"
brew "qt5"
brew "reattach-to-user-namespace"
brew "rlue/utils/timer"
brew "shellcheck"
brew "spark"
brew "stow"
brew "the_silver_searcher"
brew "vim"
brew "watch"
brew "wget"

cask "alfred"
cask "flux"
cask "google-chrome"
cask "iterm2"
cask "java"
cask "jetbrains-toolbox"
cask "mactex-no-gui"
cask "rectangle"
cask "slack"
cask "spotify"
cask "spotify-notifications"
cask "texshop"
cask "trailer"
cask "unshaky"

# add license to:
cask "airserver"
cask "sublime-text"
cask "vanilla"
