tap "goles/battery"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"

brew "bat"
brew "black"
brew "diff-so-fancy"
brew "fortune"
brew "fzf"
brew "git"
brew "github/gh/gh"
brew "gnupg"
brew "goles/battery/battery"
brew "heroku/brew/heroku"
brew "icdiff"
brew "jq"
brew "less"
brew "miller"
brew "moreutils"
brew "pylint"
brew "python"
brew "rbenv"
brew "ruby-build"
brew "shellcheck"
brew "spark"
brew "stow"
brew "the_silver_searcher"
brew "universal-ctags/universal-ctags/universal-ctags", args: ['HEAD']
brew "vim"
brew "watch"
brew "watson"
brew "wget"
brew "yoannmoinet/brews/notee"
brew "zsh"

cask "discord"
cask "flux"
cask "font-jetbrains-mono"
cask "google-chrome"
cask "iterm2"
cask "jetbrains-toolbox"
cask "mactex-no-gui"
cask "rectangle"
cask "slack"
cask "spotify"
cask "texshop"

# add license to:
cask "alfred"
cask "sublime-text"
cask "vanilla"
cask "rocket"
