tap "goles/battery"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

brew "git"
brew "goles/battery/battery"
brew "python"
brew "reattach-to-user-namespace"
brew "spark"
brew "stow"
brew "the_silver_searcher"
brew "watch"
brew "wget"

cask "alfred"
cask "flux"
cask "google-chrome"
cask "iterm2"
cask "java"
cask "jetbrains-toolbox"
cask "slack"
cask "spectacle"
cask "spotify"
cask "spotify-notifications"

# add license to:
cask "air-server"
cask "sublime-text"
cask "vanilla"
