name: Validate Ruby version

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ruby_version:
    runs-on: macos-26
    steps:
    - uses: actions/checkout@v6
    - name: Install rbenv
      run: |
        brew install rbenv
        brew install ruby-build
    - name: Check if ruby-build can install requested version
      run: rbenv install --list-all | grep '^$(cat .ruby-version)$'

